package world.danchuo.film

import jakarta.ws.rs.GET
import jakarta.ws.rs.Path
import jakarta.ws.rs.PathParam
import jakarta.ws.rs.core.CacheControl
import jakarta.ws.rs.core.Response

/**
 * Public serving of drop frames from local disk; the URLs are generated by
 * [LocalDiskPhotoStorage.url]. Moving to S3/R2 retires this resource — URLs become absolute and a
 * CDN serves them. Reads are public (§3), frames immutable ⇒ aggressive cache; unknown key ⇒ 404.
 */
@Path("/api/film-media")
class FilmMediaResource(
    private val storage: PhotoStorage,
) {

    @GET
    @Path("/{dropId}/{seq}/{variant}")
    fun media(
        @PathParam("dropId") dropId: Long,
        @PathParam("seq") seq: Int,
        @PathParam("variant") variant: String,
    ): Response {
        val v = PhotoVariant.entries.firstOrNull { it.name.equals(variant, ignoreCase = true) }
            ?: return Response.status(Response.Status.NOT_FOUND).build()
        val bytes = storage.get("$dropId/$seq", v)
            ?: return Response.status(Response.Status.NOT_FOUND).build()

        // A frame is immutable at its key (a new upload means a new drop/seq) — cache it long.
        val cache = CacheControl().apply {
            maxAge = 60 * 60 * 24 * 30 // 30 days
            isPrivate = false
        }
        return Response.ok(bytes, "image/jpeg").cacheControl(cache).build()
    }
}
