/**
 * Wave 03 "PRIME" — dark glass over the ribbon of lived days: its own palette and a board where
 * most tiles ask for their own edition (sheet, field, echo, shaft, carousel…). DESIGN §10.2
 */

import type { Wave } from "./index";

export const WAVE_03: Wave = {
  key: "wave-03",
  name: "Волна 03 «PRIME»",
  releasedAt: "2026-09-02",
  tokens: {
    "accent": "#6fe3ff",
    "accent-clean": "#58d9a6",
    "accent-code": "#8fd964",
    "accent-warm": "#9d8cff",
    "bg-page": "#0a0e14",
    "bg-surface": "#161e27",
    "bg-surface-2": "#19212b",
    "bg-surface-muted": "#0e151d",
    "border": "rgba(180, 210, 230, 0.14)",
    "border-pixel": "#cfe4f0",
    "border-tile": "rgba(160, 205, 230, 0.22)",
    "cal-othermonth": "#080d13",
    "cal-roll-ms": "200ms",
    "cal-roll-shift": "30px",
    "cal-weekend": "#090f16",
    "danger": "#ff7a6b",
    "find-negative": "invert(1) sepia(0.6) hue-rotate(155deg) saturate(1.5)",
    "drop-2": "drop-shadow(0 1px 1px rgba(0, 0, 0, 0.5)) drop-shadow(0 7px 11px rgba(0, 0, 0, 0.5))",
    "drop-3": "drop-shadow(0 2px 1px rgba(0, 0, 0, 0.55)) drop-shadow(0 12px 18px rgba(0, 0, 0, 0.55))",
    "drop-4": "drop-shadow(0 3px 2px rgba(0, 0, 0, 0.6)) drop-shadow(0 18px 26px rgba(0, 0, 0, 0.6))",
    "elev-1": "0 1px 2px rgba(0, 0, 0, 0.5)",
    "elev-2": "0 1px 2px rgba(0, 0, 0, 0.4), 0 6px 14px rgba(0, 0, 0, 0.45), 0 14px 30px rgba(0, 0, 0, 0.4)",
    "elev-3": "0 2px 4px rgba(0, 0, 0, 0.45), 0 10px 22px rgba(0, 0, 0, 0.5), 0 24px 48px rgba(0, 0, 0, 0.45)",
    "font-display": "var(--font-mono)",
    "glass-blur": "11px",
    "glass-edge": "rgba(160, 205, 230, 0.18)",
    "glass-sheen": "rgba(190, 230, 250, 0.22)",
    "glass-tint": "rgba(120, 160, 190, 0.13)",
    "pixel-corners": "polygon(0 8px, 4px 8px, 4px 4px, 8px 4px, 8px 0, calc(100% - 8px) 0, calc(100% - 8px) 4px, calc(100% - 4px) 4px, calc(100% - 4px) 8px, 100% 8px, 100% calc(100% - 8px), calc(100% - 4px) calc(100% - 8px), calc(100% - 4px) calc(100% - 4px), calc(100% - 8px) calc(100% - 4px), calc(100% - 8px) 100%, 8px 100%, 8px calc(100% - 4px), 4px calc(100% - 4px), 4px calc(100% - 8px), 0 calc(100% - 8px))",
    "px": "4px",
    "radius-lg": "20px",
    "radius-md": "12px",
    "radius-sm": "6px",
    "success": "#46c58c",
    "surface-fill": "linear-gradient(180deg, var(--bg-surface), var(--bg-surface-2))",
    "surface-othermonth": "linear-gradient(180deg, #0e151d, #090f16)",
    "text-primary": "#e9f1f7",
    "text-secondary": "#9fb0bf",
    "text-tertiary": "#93a5b4",
    "tile-depth": "0px",
    "tile-inner": "1px",
    "tile-inner-color": "rgba(190, 230, 250, 0.16)",
    "tile-line": "1px",
    "tile-slab-1": "#1b2530",
    "tile-slab-2": "#121a23",
    // The tier list keeps tiermaker's own ladder: the colours ARE the genre. PRD §5.20
    "tier-s": "#ff7f7f",
    "tier-a": "#ffbf7f",
    "tier-b": "#ffdf7f",
    "tier-c": "#ffff7f",
    "tier-d": "#bfff7f",
    "tier-ground": "#1a1a17",
    "tier-line": "#000000",
    "tier-ink": "#111111",
  },
  layout: {
    gallery: "roll",
    tiles: {
      identity: { hidden: true },
      latestDrop: { col: 1, row: 1, colSpan: 11, rowSpan: 16, edition: "frame" },
      freshness: { hidden: true },
      // Between the calendar and the projects, one track clear of each; bottom-aligned with the
      // calendar and one row shorter.
      waveSwitcher: { col: 30, row: 22, colSpan: 3, rowSpan: 6, orientation: "vertical" },
      music: { col: 13, row: 1, colSpan: 10, rowSpan: 6 },
      photoDrops: { col: 32, row: 9, colSpan: 8, rowSpan: 9, edition: "carousel" },
      stats: { col: 2, row: 19, colSpan: 10, rowSpan: 9, hidden: false, edition: "ghosts" },
      sleep: { col: 33, row: 1, colSpan: 8, rowSpan: 7, hidden: false, edition: "echo" },
      today: { col: 14, row: 9, colSpan: 16, rowSpan: 11, hidden: false, edition: "sheet" },
      calendar: { col: 20, row: 21, colSpan: 9, rowSpan: 7, hidden: false, edition: "field" },
      projects: { col: 34, row: 23, colSpan: 7, rowSpan: 6, edition: "console", planet: "model" },
      ride: { hidden: true },
      hero: { hidden: true },
      // Two bare marks stacked in the two-track gap between the music and the feedback, one empty row
      // between them. The stack keeps the same two marks, not the whole plate.
      social: { only: "stack", edition: "peek", platforms: ["telegram", "instagram"] },
      socialTelegram: { col: 23, row: 1, colSpan: 2, rowSpan: 2, hidden: false, only: "bento", edition: "peek" },
      socialInstagram: { col: 23, row: 4, colSpan: 2, rowSpan: 2, hidden: false, only: "bento", edition: "peek" },
      socialGithub: { hidden: true },
      socialX: { hidden: true },
      marquee: { col: 13, row: 21, colSpan: 7, rowSpan: 8, hidden: false, edition: "shaft" },
      // Top row between the music and the sleep tile: what the board is, then the call for a note
      // under a rule. DESIGN §7.11
      feedback: { col: 25, row: 1, colSpan: 7, rowSpan: 5, edition: "intro" },
      // The shirt tier list: a wide door over the projects, the ladder plus words saying it is shirts.
      tierlist: { col: 34, row: 19, colSpan: 7, rowSpan: 3, hidden: false },
    },
    mobileOrder: [
      "feedback",
      "today",
      "calendar",
      "sleep",
      "music",
      "stats",
      "latestDrop",
      "photoDrops",
      "social",
      "projects",
      "marquee",
      "tierlist",
      "waveSwitcher",
    ],
  },
};
